config/routes.rb
Rails.application.routes.draw do
	root to:'home#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :books
 resources :users
 resources :homes
 get 'home/about'=>'home#about'
 get '/search' => 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, length:{in: 1..200 }, allow_blank: true
    validates :body, presence: true
    belongs_to :user
    def self.search(search)
      return Book.all unless search
      Book.where(['content LIKE ?', "%#{search}%"])
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence:true, length:{in:2..20}
  validates :introduction, length:{maximum:50}
  def self.search(search) #self.はUser.を意味する
     if search
       User.where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
     else
       User.all #全て表示させる
    end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, only: [:show]
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_out_path_for(resource)
	
  	flash[:notice] = "Signed out successfully."
  	 root_path
  end
  def after_sign_in_path_for(resource)
    user_path(current_user)
end


	protected

		def configure_permitted_parameters
		    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
		    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
		end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]
 
  def index
   @books=Book.all
   @book=Book.new
   @user=current_user
 end

 def show
   @book1=Book.find(params[:id])
   @books=Book.all
   @user=Book.find(params[:id]).user
   @book=Book.new
 end
 def create
  @user=current_user
  @book=Book.new(book_params)
  @book.user_id=current_user.id
  @books=Book.all
  if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
  else

    render :index
  end

end
def edit
 @book=Book.find(params[:id])
end

def update
 @book=Book.find(params[:id])
 if @book.update(book_params)
   flash[:notice] = "Book was successfully created."
   redirect_to book_path(@book.id)
 else
  render :edit
  end
end
def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to books_path
end

private
def book_params
  params.require(:book).permit(:title,:body)
end
def correct_user
    @book = Book.find(params[:id])
    if current_user != @book.user
       redirect_to books_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]

  def top
  	if current_user
        redirect_to user_path(current_user)
    end
  end

  def index
		@users=User.all
    @book=Book.new
    @user=current_user

  end
  def show
  	@user=User.find(params[:id])
  	@book1=User.find(params[:id]).books
  	 @book=Book.new
  end
  def search
    @users = User.search(params[:search])
     @book=Book.new
    @user=current_user
  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  		@user = User.find(params[:id])
  	if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
  	redirect_to user_path(@user.id)
    else
  	render :edit
    end
  end
    def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
private
  def user_params
      params.require(:user).permit(:name,:introduction,:profile_image)
    end
def correct_user
  @user=User.find(params[:id])

     redirect_to user_path(current_user) unless @user == current_user

end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/books/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, size: '100x100', format: "jpeg", fallback: "no_image.jpg" %>

<h4>name<%= @user.name %></h4>

<h4>introduction<%= @user.introduction %></h4>

<%= link_to  edit_user_path(@user), class: 'btn btn-default btn-block' do
 %>
  <i class="glyphicon glyphicon-wrench"></i>
  <span></span>
<% end %>


<h2>New book</h2>
<%= form_for (@book) do |f| %>
<% if books.errors.any? %>
<div id="erorr_explanation" >
	<ul>
		<%= books.errors.count %>errors prohibited this obj from being saved:
		<% books.errors.full_messages.each do |message| %>
		<%= message %>
		<% end %>
	</ul>
</div>
<% end %>
<label for="bookname">Title</label>
<div class="input" type="hidden"><%= f.text_field :title,placeholder:'タイトル' %></div>
<label for="bookname">Body</label>
<div class="input"><%= f.text_area :body, placeholder:'本文' %></div>
<%= f.submit 'Create Book' ,class: "btn btn-primary"%>
<% end %>
<p>検索</p>
<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

app/views/books/_seach.html.erb
<p>検索</p>
<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<ul><% @books.each do |post| %>
  <li>
    <%= link_to book.title, post %>
    <%= book.created_at %>
    <%= book.status %>
  </li>
  <%= link_to "編集",edit_post_path(post) %>
  <%= link_to "削除",post, method: :delete %>
  <% end %>
</ul>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
<H1>Editing Book</H1>
<%= form_for (@book) do |f|%>
<% if @book.errors.any? %>
<div id="erorr_explanation" >
	<ul>
		<%= @book.errors.count %>errors prohibited this obj from being saved:
		<% @book.errors.full_messages.each do |message| %>
		<%= message %>
		<% end %>
	</ul>
</div>
<% end %>

<h4>Title:</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %></p>

<%= f.submit 'Update Book' %>
<% end %>
<td><%= link_to "Show", book_path(@book.id) %></td>
<a href="/books" style="color:black">Back</a>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
<header></header><!-- /header -->
  <div class="container"> <!-- ここを追加 -->
      <div class="row">   <!-- ここを追加 -->
      	 <div class="col-xs-3">
<%= render'books/list',books:@book %>

</div>
<div class="col-xs-9">
<p id="notice"></p>
	<h1>Books</h1>
	<table class="table table-striped">
	<thead >
		<tr>
			<th>Image</th>
			<th>Title</th>
			<th>Body</th>
			<th colspan="1"></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= link_to user_path(book.user) do %>
				<%= attachment_image_tag book.user, :profile_image,size: '100x100', format: 'jpeg',fallback:"no_image.jpg" %>
					<% end %>
				</td>
			<td><%= link_to book.title,book_path(book.id) %></td>
			<td><%= book.body %></td>
			<td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure？",style:"color:black"%></td>
		</tr>
		<% end %>
		<br>
	</tbody>
</table>
</div>
</div>
</div>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>



<div class="container"> <!-- ここを追加 -->
      <div class="row">   <!-- ここを追加 -->
      	 <div class="col-xs-3">
<%= render'books/list',books:@book %>
</div>
<div class="col-xs-9">


<body>
 <% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end %>
</html>
<h2>Book detail</h2>

<table lass="table table-striped">
	<thead >
		<tr>
			<th>Image</th>
			<th>name</th>
			<th>title</th>
			<th>body</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
		<tr>
<td><%= link_to user_path(@user) do %>
	<%= attachment_image_tag @user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
		<% end %>
	</td>
<td><%= link_to user_path(@user) do %>
	<%= @user.name  %>
		<% end %>
	</td>

<td><%= @book1.title %></td>

<td><%= @book1.body %></td>
<% if current_user == @user %>
<td><%= link_to "Edit",edit_book_path(@book1.id) %></td>
<td><%= link_to "Destroy", book_path(@book1.id), method: :delete, "data-confirm" => "Are you sure？",style:"color:black"%></td>
<% end %>
</tr>
</tbody>
</table>


</div>
</div>
</div>

</body>

app/views/books/top.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<h1>ようこそ Bookers へ!</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p>
	<a href="/books">start</a>
</p>
</body>
</html>

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>

</body>
</html>

app/views/home/top.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end %>
<h1>welcome to Bookers !!</h1>
<p>In<strong><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers</strong>でyou can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
<div class=container>
	<div class="row">
		  <%= link_to "Log In", new_user_session_path,class: "btn btn-primary btn-block"%>
      <%= link_to "Sign UP", new_user_registration_path,class: "btn btn-success btn-block" %>
  </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header class="navbar navbar-fixed navbar-inverse navbar-block">
  <div id="container">
    <nav class="nav navbar-left text-success">
    <h3>Bookers</h3>
  </nav>
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
      <li class="">
        <%= link_to 'Home', user_path(current_user),class:"glyphicon glyphicon-home " %>
      </li>
      <li class="">
          <%= link_to 'Users', users_path,class:"glyphicon glyphicon-user"%>
      </li>
      <li class="">
        <%= link_to "Books", books_path,class:"glyphicon glyphicon-book" %>
      </li>
       <li class="">
         <%= link_to "logout", destroy_user_session_path,class:"glyphicon glyphicon-log-out", method: :delete%>
      </li>
    <% else %>
      <li class="">
        <%= link_to "Home", root_path,class:"glyphicon glyphicon-home"%>
      </li>
      <li class="">
        <%= link_to "About", home_about_path,class:"glyphicon glyphicon-link"%>
      </li>
      <li class="">
        <%= link_to "Sign Up", new_user_registration_path,class:"glyphicon glyphicon-new-window"  %>
      </li>
      <li class="">
             <%= link_to " Login", new_user_session_path,class:"glyphicon glyphicon-log-in"%>
      </li>
    <% end %>
  </ul>
</div>
</header>


    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1 class="jquery">Hello jQuery</h1>
<h1>User info</h1>
<%= form_for (@user) do |f| %>
<% if @user.errors.any? %>
        <%= @user.errors.count %>件のerrorが発生しました
        <% @user.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>

<h2>Name</h2>
<div class="input"><%= f.text_field :name %></div></div>
<h2>image</h2>
<%= f.attachment_field :profile_image %>

<h2>Introduction</h2>
<div class="input"><%= f.text_field :introduction %></div>
<%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end %>
<div class="container">
      <div class="row">
      	 <div class="col-xs-3">
<%= render'books/list',books:@book %>
</div>
<div class="col-xs-9">
<table class="table table-striped">
	<thead>
		<tr>
			<th>Image</th>
			<th>name</th>
			<th colspan="1"></th>
		</tr>
	</thead>
	<tbody>
		<h1>Users</h1>
		<% @users.each do |list| %>
		<tr>
			<td><%= attachment_image_tag list, :profile_image,size: '100x100', format:"jpeg",fallback:"no_image.jpg" %></td>
			<td><%= list.name %></td>
			<td><%= link_to "Show", user_path(list.id)%></td>
		</tr>
		<% end %>
		<br>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/search.html.erb
<!DOCTYPE html>
<html>
<header></header><!-- /header -->
  <div class="container"> <!-- ここを追加 -->
      <div class="row">   <!-- ここを追加 -->
      	 <div class="col-xs-3">
<%= render'books/list',books:@book %>
</div>
<div class="col-xs-9">
<table class="table table-striped">
<ul><% @users.each do |user| %>
  <li>
    <%= link_to user.name %>
    <%= user.created_at %>
  </li>
  <%= link_to "編集",edit_user_path(user) %>
  <%= link_to "削除",user, method: :delete %>
  <% end %>
</ul>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end %>
<div class="container"> <!-- ここを追加 -->
      <div class="row">   <!-- ここを追加 -->
      	 <div class="col-xs-3">
<%= render'books/list',books:@book %>
</div>
<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-striped">
	<thead >
		<tr>
			<th>Image</th>
			<th>Title</th>
			<th>opinion</th>
		</tr>
	</thead>
	<tbody>
		<% @book1.each do |list| %>
		<tr>
			<td><%= attachment_image_tag @user,:profile_image,size: '100x100',format:"jpeg",fallback:"no_image.jpg"%></td>
			<td><%= link_to list.title,book_path(list.id) %></td>
			<td><%= list.body %></td>
		</tr>
		<% end %>
		<br>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/top.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
	<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end %>
<h1>welcome to Bookers !!</h1>
<p>In<strong>Bookers2</strong>でyou can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
<p>
	<li class="">
		  <%= link_to "Log in", new_user_session_path %>
      </li>
      <li class="">
        <%= link_to "Sign UP", new_user_registration_path %>
      </li>
</p>
</body>
</html>